// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFo24wlxYhMTSkWOCJKRQN83yT2XblfmE',
    appId: '1:623204910695:web:5177fc0b4dc6219793f6c2',
    messagingSenderId: '623204910695',
    projectId: 'foodshop-c3341',
    authDomain: 'foodshop-c3341.firebaseapp.com',
    databaseURL: 'https://foodshop-c3341-default-rtdb.firebaseio.com',
    storageBucket: 'foodshop-c3341.appspot.com',
    measurementId: 'G-T34CB7NJZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW-XENvewruof82aQXxZWOnoNkE9BkPkU',
    appId: '1:623204910695:android:e371a3664149769b93f6c2',
    messagingSenderId: '623204910695',
    projectId: 'foodshop-c3341',
    databaseURL: 'https://foodshop-c3341-default-rtdb.firebaseio.com',
    storageBucket: 'foodshop-c3341.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLh4Bkc-qTY8q1YrhIS-Rar5YGr_Kw_WU',
    appId: '1:623204910695:ios:df52ac3a324bca9293f6c2',
    messagingSenderId: '623204910695',
    projectId: 'foodshop-c3341',
    databaseURL: 'https://foodshop-c3341-default-rtdb.firebaseio.com',
    storageBucket: 'foodshop-c3341.appspot.com',
    androidClientId: '623204910695-56j66qhd4u2888qfe14tkt9e2eumv2k2.apps.googleusercontent.com',
    iosClientId: '623204910695-9i10vi6a6uk1o4oe85t60asovopipq74.apps.googleusercontent.com',
    iosBundleId: 'com.unknown.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLh4Bkc-qTY8q1YrhIS-Rar5YGr_Kw_WU',
    appId: '1:623204910695:ios:df52ac3a324bca9293f6c2',
    messagingSenderId: '623204910695',
    projectId: 'foodshop-c3341',
    databaseURL: 'https://foodshop-c3341-default-rtdb.firebaseio.com',
    storageBucket: 'foodshop-c3341.appspot.com',
    androidClientId: '623204910695-56j66qhd4u2888qfe14tkt9e2eumv2k2.apps.googleusercontent.com',
    iosClientId: '623204910695-9i10vi6a6uk1o4oe85t60asovopipq74.apps.googleusercontent.com',
    iosBundleId: 'com.unknown.social',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFo24wlxYhMTSkWOCJKRQN83yT2XblfmE',
    appId: '1:623204910695:web:dd329b2f7da6537b93f6c2',
    messagingSenderId: '623204910695',
    projectId: 'foodshop-c3341',
    authDomain: 'foodshop-c3341.firebaseapp.com',
    databaseURL: 'https://foodshop-c3341-default-rtdb.firebaseio.com',
    storageBucket: 'foodshop-c3341.appspot.com',
    measurementId: 'G-4QVVMEY72E',
  );
}
